### PR TITLE
blb made some progress on Zen.

### PR DESCRIPTION
**Pull request by orn8**
They are closer to level 500,000. Currently at 11,857 (as shown [here](https://ch.tetr.io/u/blb)), there are 488,103 levels left (instead of the previous 409k levels).

### CODE REVIEW

**Comment by ZaptorZap** [comment]
yyyyyyyeah there's only so much we can do here and manually updating it is definitely not happening.

**Comment by orn8** [comment]
ok lol

**Comment by orn8** [comment]
but they left tetr.io for 3 years now.

**Comment by ZaptorZap** [comment]
If you look at the [commit history](https://github.com/tetrio/faq/commits/main/terminology.html) for that file, you'll see that this file isn't 3 years old. That level _has changed since_ and we're not going to closely track it.

**Pull request closed without merging**
